//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uslugiEntities1 : DbContext
    {
        public uslugiEntities1()
            : base("name=uslugiEntities1")
        {
        }

        private static uslugiEntities1 _context;
        public static uslugiEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new uslugiEntities1();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<uslugi> uslugis { get; set; }
        public virtual DbSet<uslugi_client> uslugi_client { get; set; }
    }
}
