//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class uslugi_client
    {
        public int код_услуги { get; set; }
        public int код_оказания_услуги { get; set; }
        public Nullable<System.DateTime> Начало_услуги { get; set; }
        public Nullable<System.DateTime> время { get; set; }
        public Nullable<int> код_клиента { get; set; }
    
        public virtual client client { get; set; }
        public virtual uslugi uslugi { get; set; }
    }
}
